[package]
name = "poem-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = "1.2.26"
tokio = { version = "1.15.0", features = ["full"] }
tracing-subscriber = "0.2.24"
